application:
  bindAddress: :8447
  production: false
  debug: false
database:
  address: localhost:3400
  name: inventory
  username: admin
  password: admin
authentication:
  authority: https://algotiqa-server:8443/auth/realms/algotiqa
  clientId: algotiqa-backend
  clientSecret: xyz
platform:
  system: https://algotiqa-server:8449/api/system
messaging:
  address: localhost:8450
  username: admin
  password: admin
provider:
  currency:
    baseUrl: https://api.freecurrencyapi.com/v1
    apiKey : fca_live_PEgz9oUDbBGePkYR5UtVnhAU739eVYptqKvC9mTd
